openwsn-berkeley/openwsn-fw

bsp/boards/openmotestm/configure/stm32f10x_it.c, bsp/boards/openmotestm/leds.c, bsp/boards/openmotestm/nvic.c, bsp/boards/openmotestm/uart.c
Fixed the led and uart driver for new openmotestm.
=> Develop fw 329

openstack/04-TRAN/opencoap.c, openstack/04-TRAN/opencoap.h
See comments in commit to merge.
=> FW-331. Improve CoAP request/response matching.

openapps/cexample/cexample.c
=> FW-332. Fix cexample message formatting.

bsp/boards/common/aes_cbc.c
This pull request fixes the bug in firmware implementation of CBC encryption.
=> FW-353. Fix raw CBC encryption.

inc/opendefs.h, openapps/SConscript, openapps/openapps.c, openapps/uinject/uinject.c, openapps/uinject/uinject.h, openapps/uinject/uinject.py, openapps/uinject/uinject_dagroot.py, openstack/04-TRAN/openudp.c, openstack/SConscript, projects/python/SConscript.env
Adding default `uinject` application which sends a counter to the DAGroot every 30s.
=> FW-347. Fix.

openstack/03a-IPHC/iphc.c
Reverts openwsn-berkeley/openwsn-fw#196
=> Revert "FW-406. Fixed."

openstack/02b-MAChigh/sixtop.c
At the beginning the tx attempts left are now TXRETRIES plus one.
=> FW-431. Fix.

openstack/03b-IPv6/icmpv6rpl.c, openstack/03b-IPv6/icmpv6rpl.h
=> FW-442. Fix. DIO and DAO period randomness

bsp/boards/telosb/SConscript, bsp/boards/telosb/adc_sensor.c, bsp/boards/telosb/adc_sensor.h, bsp/boards/telosb/sensors.c, bsp/chips/sht11/SConscript, bsp/chips/sht11/sht11.c, bsp/chips/sht11/sht11.h
I created all functions to implement the sensor on TelosB. Only light sensors are working at this time, but it will be easy to extend the implementation to other sensor later.
=> FW-466. implemented light sensor functions for TelosB platform

openapps/uinject/uinject.c, openapps/uinject/uinject.py
And fixed 'uinject.py' script to read both ASN and the counter.
=> FW-468. Fixed the way counter is written in the uinject app. 

openstack/02a-MAClow/IEEE802154_security.c, openstack/cross-layers/packetfunctions.c, openstack/cross-layers/packetfunctions.h
This PR creates security nonce using big endian format of ASN.
=> FW-433. Big endian format for ASN part of the security nonce.

openapps/opencoap/openoscoap.c
This fixes the issue with key identifier in OSCOAP's implementation in OpenWSN.
=> FW-667. Fix key identifier passed in AAD of OSCOAP.

openstack/03b-IPv6/icmpv6rpl.c, openstack/03b-IPv6/icmpv6rpl.h
this is adding PIO option to the DIO. Tested with OpenMotes during plugtest.
=> Develop fw 668

openstack/02a-MAClow/IEEE802154E.c, openstack/02a-MAClow/IEEE802154E.h
In some case, i need to use less channel instead of 16 channels.
=> FW-666 Easy channel hopping template modify

openapps/cinfo/cinfo.c
representation of cinfo minor version number corrected
=> FW-688. cinfo version representation requires fix.

projects/common/03oos_sniffer/03oos_sniffer.c
Sniffer is sometimes missing packets. Having shorter TIME_PERIOD can help fix this problem.
- Trivial whitespace fixes embedded
=> FW-706. Having short sniffer TIME_PERIOD

openapps/opencoap/opencoap.c, openapps/opencoap/opencoap.h, openapps/opencoap/openoscoap.c
this PR supports additional coap options to be used which have an index smaller than COAP_OPTION_NUM_URIPATH. It also handles multiple coap option of the same kind.
=> FW-681. Fixed handling of coap options

openapps/uinject/uinject.c, openapps/userialbridge/userialbridge.c, openstack/02a-MAClow/IEEE802154E.c, openstack/02a-MAClow/IEEE802154_security.c, openstack/02a-MAClow/adaptive_sync.c, openstack/02b-MAChigh/neighbors.c, openstack/02b-MAChigh/schedule.c, openstack/02b-MAChigh/sixtop.c, openstack/03a-IPHC/iphc.c, openstack/03a-IPHC/openbridge.c, openstack/03b-IPv6/forwarding.c, openstack/03b-IPv6/icmpv6.c, openstack/03b-IPv6/icmpv6echo.c, openstack/03b-IPv6/icmpv6rpl.c, openstack/04-TRAN/openudp.c, openstack/cross-layers/idmanager.c, openstack/cross-layers/openqueue.c, openstack/cross-layers/openrandom.c, projects/agilefox/00std_low_power_mode/00std_low_power_mode.c, projects/gina/02drv_headsup/02drv_headsup.c, projects/gina/old/imu_loop.c, projects/gina/old/test_hybrid_arq.c, projects/gina/old/test_pwm.c, projects/gina/old/test_radio.c, projects/openmotestm/00std_low_power_mode/00std_low_power_mode.c, projects/telosb/00std_eui64/00std_eui64.c, projects/wsn430v13b/00std_eui64/00std_eui64.c
=> Fix "old-style function definition" warning all over the repo part 2

openstack/02a-MAClow/IEEE802154E.c
Description provided in title.
=> Bugfix introduced in #411. Change back to default channel hopping.

openstack/02a-MAClow/IEEE802154E.c
Quick fix for calculating the correct asnOffset.
=> FW-757: Calculating wrong frequencies when NUM_CHANNELS differs from 16
