openwsn-berkeley/openwsn-fw

- bsp/boards/OpenMote-CC2538/cc2538_crypto_engine.c
- projects/OpenMote-CC2538/SConscript.env
This pull request adds the implementation of CCM functions that leverage hardware acceleration specific to CC2538. This crypto engine is used by default for CC2538 motes.
> FW-370. Crypto hardware acceleration for OpenMote-CC2538.

- bsp/chips/cc2420/cc2420.c
- bsp/chips/cc2420/cc2420.h
- bsp/chips/cc2420/radio.c
This pull request implements functions that read and write CC2420 RAM over SPI. 
Additionally, it modifies ```radio_spiWriteTxFifo()``` in order to generalize it and allow write access to RX FIFO, by accepting the register address argument. Write access to RX FIFO is needed for in-line decryption of CC2420.
> FW-371. Implement functions to read and write RAM on CC2420.

- bsp/boards/telosb/SConscript
- bsp/boards/telosb/board_crypto_engine.c
- bsp/boards/telosb/board_crypto_engine.h
- bsp/chips/cc2420/SConscript
- bsp/chips/cc2420/cc2420.c
- bsp/chips/cc2420/cc2420.h
- bsp/chips/cc2420/cc2420_crypto.c
- bsp/chips/cc2420/cc2420_crypto.h
- bsp/chips/cc2420/radio.c
- projects/common/01bsp_cryptoengine/01bsp_cryptoengine.c
- projects/telosb/SConscript.env
This pull request implements CC2420 hardware-accelerated encryption functions and uses it for TelosB's crypto engine. Stand-alone, 16 byte AES buffer of CC2420 is used for ECB encryption mode. CCM* is implemented by leveraging the in-line functionality of CC2420. CCM* encryption/decryption take place in TX/RX FIFO buffers, respectively. The implementation successfully passes the test suite but has not been fully optimized yet.
> FW-372. Crypto hardware acceleration for CC2420 boards.

- bsp/chips/cc2420/cc2420.c
- bsp/chips/cc2420/cc2420.h
- bsp/chips/cc2420/cc2420_crypto.c
- bsp/chips/cc2420/radio.c
This PR prefixes the functions in ```chips/cc2420/cc2420.c``` library with ```cc2420_``` instead of ```radio_``` in order to match the new structure.
> FW-373. Prefix cc2420.c functions with 'cc2420_'.

- projects/python/SConscript.env
Fixes https://openwsn.atlassian.net/browse/FW-375
The compiler warnings get eliminated according to https://docs.python.org/3.2/c-api/intro.html#include-files by making sure that `Python.h` is always included first.
> always include Python.h first

- SConscript
- bootloader/iot-lab_M3/README
- bootloader/iot-lab_M3/iotlab-m3-bsl.py
- bootloader/iot-lab_M3/iotlab-m3.cfg
This PR implements the Python version of bootloading script for IoT-LAB_M3 nodes and integrates it with the OpenWSN scons build.
Since programming of IoT-LAB_M3 nodes is done using openocd, which to my knowledge does not support interfacing with devices over /dev/ttyUSB* or COMX ports, the BSL script flashes the first IoT-LAB_M3 node found connected to the PC, independent of the bootload argument passed to SCons.
The PR also contains a README file  (bootloader/iot-lab_M3/README) that explains the necessary steps in order to configure the Windows environment. 
To flash an IoT-LAB_M3 node, the user should follow  the typical OpenWSN workflow with bootload option present:
scons board=iot-lab_M3 toolchain=armgcc bootload=0 oos_openwsn
> FW-379. Integrate bootloader for IoT-LAB_M3 motes.

- openstack/02a-MAClow/IEEE802154.c
- openstack/02a-MAClow/IEEE802154.h
- openstack/02a-MAClow/IEEE802154E.c
- openstack/02a-MAClow/IEEE802154E.h
- projects/python/SConscript.env
Move timeCorrection IE into header.
> FW-392. Fixed.

- openstack/03b-IPv6/forwarding.c
Update l4_protocol_compressed by next_header_compressed of ipv6 inner header.
> FW-394. Fixed.

- openstack/02b-MAChigh/neighbors.c
This PR splits the ```rankIncrease``` calculation into several steps and uses fixed point arithmetics instead of floating point operations.
> FW-425. Fix. Replace the usage of float with fixed point arithmetics.

- bsp/chips/at86rf231/radio.c
In bsp/chips/at86tf231/radio.c, added a write to radio register in order to setup TX power at initialization instead of staying with the hardware reset default value.
> FW-459. Added a write to radio register at init

- openstack/02b-MAChigh/neighbors.c
In the calculation of the tentativeDAGrank in
neighbors_updateMyDAGrankAndNeighborPreference an overflow was possible.
This results in occasional choosing a preferred parent with MAXDAGRANK.
> FW-449. Fixing overflow in DAGrank calculation

- openstack/03a-IPHC/iphc.c
- openstack/03a-IPHC/iphc.h
- openstack/03b-IPv6/forwarding.c
Placing an unknown RHE between the page dispatch and RH3s caused the motes to crash. This fix should allow them to forward it unchanged.
> FW-479. unknown RHE are now forwarded by the motes.

- SConscript
- SConstruct
- projects/OpenMote-CC2538/cc2538_gdb.gdb
- tools/qtcreator.py
- tools/qtcreator/OpenWSN.config
- tools/qtcreator/OpenWSN.creator
- tools/qtcreator/OpenWSN.creator.user
this adds a new functionality to scons builder system. By specifying the [ide] e.g., ide=qtcreator the IDE is configured automatically according to the board we are compiling. for example
scons board=OpenMote-CC2538 toolchain=armgcc ide=qtcreator oos_openwsn. 
this runs qtcreator (must be in the path) configured for the openmote platform. We can run it for gina, telosb, etc...
qtcreator is opensource and can be downloaded from here 
http://www.qt.io/download-open-source/
or installed in linux by
sudo apt-get install qtcreator
no need to register, just skip and have fun. it is a lightweight and fast ide with very nice functionalities.
It is tested in windows and linux. Note that qtcreator must be in the path.
> ADM-62 adding ide functionality to scons builder

- openstack/04-TRAN/opencoap.c
* Use an ACK response only for a CON request.
> FW-497. For CoAP, use a NON type response for a NON type request.

- SConscript
- SConstruct
- openstack/cross-layers/idmanager.c
================= example  ======================================
C:\Users\in\Desktop\work\openwsn-fw>scons board=python panid=0x2FD8 toolchain=gc
c oos_openwsn
scons: Reading SConscript files ...
__            __     _ _ _  ___  _ _
| .\ ___      |  |   | | | |/ __>| \ |
|   || . \    _| |   | | | |\__ \|   |
`__/'|  _/  \____/   |__/_/ <___/|_\_|
|_|\_\                openwsn.org
none
scons: done reading SConscript files.
scons: Building targets ...
Compiling (shared) build\python_gcc\projects\common\03oos_openwsn\03oos_openwsn_
obj.o
.................
.................
.................
Compiling          build\python_gcc\bsp\boards\common\dummy_crypto_engine.o
gcc -shared -o build\python_gcc\projects\common\oos_openwsn.pyd build\python_gcc …
> FW-577. Set the PANID at compilation time.

- bsp/chips/cc2420/radio.c
TelosB mote is on for 1ms too long because radio_rxEnable() is called
in activity_ri2 rather than activity_ri3.
> FW-583. TelosB mote is on for 1ms too long because radio_rxEnable() is called in activity_ri2 rather than activity_ri3.

- openstack/02a-MAClow/IEEE802154E.c
- openstack/02b-MAChigh/processIE.c
In IEEE802154e.c and processIE.c, there are some typos related to timeslot template ID and channelhopping template ID at some comments.
> correct comments that has some typos

- openapps/opencoap/opencoap.c
This PR passes error responses to the application even though they are unprotected by OSCOAP.
> FW-696. Pass unencrypted CoAP errors to the application.

- openapps/cjoin/cjoin.c
With this PR, OSCOAP security context is initialized just before sending the Join Request. This fixes the issue of not using the key configured over serial for sending the Join Request.
> FW-697. Initialize OSCOAP context just before sending the Join Request.

- openstack/02b-MAChigh/neighbors.c
This PR modifies the policy by which a Join Proxy is selected by requiring it to be a stable neighbor.
> FW-699. Join Proxy must be a stable neighbor.

- openstack/02a-MAClow/IEEE802154_security.c
In the case when SECJOIN is used without L2SEC, this PR ensures that EBs are sent only once the node has received the Join Response.
> FW-701. Allow L2SEC to be configured even when it is not used.

- openapps/cjoin/cjoin.c
- openstack/02a-MAClow/IEEE802154_security.c
- openstack/02a-MAClow/IEEE802154_security.h
- projects/python/SConscript.env
This PR solves the issue of intermediate nodes not sending EBs when cjoin app is not used.
> FW-701. Introduce a flag to signal presence of dynamic keying support.

- bootloader/telosb/bsl
There are also some automatic trailing whitespaces fixes
> FW-704 - Assign to serial.baudrate instead of setBaudrate

- .travis.yml
The microcontroller ROM size is limited for telosb, wsn430v13b and wsn430v14 platform. Do not compile oos_openwsn project for those platforms.
> FW-613. do not compile for telosb, wsn430v13b and wsn430v14 

- drivers/common/openserial.c
`id` is not used. When compiled from RIOT this throws an `unused parameter` error.
> drivers/openserial: fix unused parameter `id`

- openstack/02a-MAClow/IEEE802154.c
- openstack/02b-MAChigh/sixtop.c
This PR sets initial values to some variables. Compiler warnings complained about potential use of uninitialized variables.
> MAC: fix potentially uninitialized variable

- projects/common/01bsp_cryptoengine/01bsp_cryptoengine.c
when running CCMS_AUTH tests output is never compared because len_m is zero for both examples, use tag_len instead
> Fix 01bsp_cryptoengine test data
